### ISSUE TITLE
Can't disable updates

### ISSUE THREAD

**Issue by GainingAccess** [basti564/Oculess#112]
Every single time I try to run the command "adb shell pm disable --user 0 com.oculus.updater" I get the following error message.

Exception occurred while executing 'disable':
java.lang.SecurityException: Shell cannot change component state for com.oculus.updater/null to 2
        at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:24176)
        at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:23978)
        at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:2194)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:240)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:40)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:24841)
        at android.os.Binder.shellCommand(Binder.java:950)
        at android.os.Binder.onTransact(Binder.java:834)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8874)
        at android.os.Binder.execTransactInternal(Binder.java:1184)
        at android.os.Binder.execTransact(Binder.java:1143)

**Comment by GainingAccess** [comment]
nevermind

**Comment by GainingAccess** [comment]
version is above v42, thats why it isnt working, sorry
