### ISSUE TITLE
com.oculus.appsafety not disabling 

### ISSUE THREAD

**Issue by AgentHV** [basti564/Oculess#5]
After disabling telemetry, `adb shell pm list packages -d` lists any package but `com.oculus.appsafety`. `adb shell pm path com.oculus.appsafety` lists appsafety too but that goes for any of the packages.

**Comment by basti564** [comment]
Hi, I don't get any output for ```adb shell pm list packages -d``` before or after I disable telemetry, but that's because I don't disable the packages, I "freeze"/hide them.
But thanks for telling me about ```com.oculus.appsafety```. I guess there is a problem while disabling it. I will look into that soon :)

**Comment by AgentHV** [comment]
First, this is probably related to my other issue because I've had disabled any of the telemetry-packages except appsafety prior using Oculess to disable even more stuff.
So when I had telemetry enabled in Oculess, `adb shell pm list packages -d` showed me the packages I had disabled when you still could disable packages as disabled while having telemetry disabled in Oculess caused this list to by empty, thus leading me to believe that the packages were enabled and therefore the buttons were swapped.
However the reason for this could also be that the frozen packages loose their disabled status while being frozen (or it isn't recognized at least).
I tested this via `adb shell pm path PACKAGENAME` too and it gave me back the path without issues, disabled or not, so there is still something not working as intended.

Conclusion:
Having some packages disabled prior using Oculess can lead to some weird stuff and **may** break something in the way Oculess freezes stuff (but I'm not sure because my setup is everything but deterministic).

**Comment by bloemer** [comment]
Hi basti564.

Thank you very much for your effort and the how to on YouTube!
During running the command, thats listed under the clip (`adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver`) I receive an error saying:

`Error: Command failed: "C:\Users\Denis\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s 1WMHH830HQ1143 shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device at android.os.Parcel.createException(Parcel.java:2079) at android.os.Parcel.readException(Parcel.java:2039) at android.os.Parcel.readException(Parcel.java:1987) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203) at com.android.commands.dpm.Dpm.onRun(Dpm.java:115) at com.android.internal.os.BaseCommand.run(BaseCommand.java:65) at com.android.internal.os.BaseCommand.run(BaseCommand.java:49) at com.android.commands.dpm.Dpm.main(Dpm.java:41) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8652) at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7821) at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)
`

Do I need to chage the name to _my organisation_ or something?

**Comment by AgentHV** [comment]
Oculess doesn't seem to work on the newer firmwares. However, this should be a new issue as you aren't mentioning the same problem.
